# Generated by Django 5.0.1 on 2024-02-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_post_image_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
