# Generated by Django 5.0.1 on 2024-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_blogpost_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
