# Generated by Django 5.0.1 on 2024-02-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_blogpost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
