# Generated by Django 5.0.1 on 2024-02-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
