# Generated by Django 5.0.1 on 2024-02-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_language_project_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='programming_language',
            new_name='prog_language_name',
        ),
    ]
