# Generated by Django 5.0.2 on 2024-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0019_rename_programming_language_language_prog_language_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
