# Generated by Django 5.0.2 on 2024-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_alter_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
