# Generated by Django 5.0.1 on 2024-02-21 10:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_snippet',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
